<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ATM_Replica</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Pages\UserDashboard.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="Pages\SignUp.cshtml" />
    <_ContentIncludedByDefault Remove="Pages\UserDashboard.cshtml" />
    <_ContentIncludedByDefault Remove="Pages\UserTransactions\CheckBalance.cshtml" />
    <_ContentIncludedByDefault Remove="Pages\UserTransactions\Deposit.cshtml" />
    <_ContentIncludedByDefault Remove="Pages\WithdrawPage.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Pages\WithdrawPage.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Pages\UserTransactions\Deposit.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Pages\UserTransactions\CheckBalance.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNet.WebPages" Version="3.3.0" />
    <PackageReference Include="MongoDB.Driver" Version="3.9.0" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Pages\SignUp.cshtml" />
  </ItemGroup>

</Project>
